language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_ABI=armeabi-v7a
    - TERM=dumb
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.1
  - android-26
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
install:
  - chmod +x gradlew
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
before_script:
  - export NDK_VERSION=r10e
  - curl -L http://dl.google.com/android/ndk/android-ndk-${NDK_VERSION}-linux-x86_64.bin -O
  - chmod u+x android-ndk-${NDK_VERSION}-linux-x86_64.bin
  - ./android-ndk-${NDK_VERSION}-linux-x86_64.bin > /dev/null
  - rm android-ndk-${NDK_VERSION}-linux-x86_64.bin
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-${NDK_VERSION}
  - export PATH=${ANDROID_NDK_HOME}:${PATH}
  - ./gradlew clean || true
script:
  - ./gradlew assembleDebug testDebug jacocoTestReport
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew connectedCheck
after_success:
  - bash <(curl -s https://codecov.io/bash)
after_failure:
  - zip -r reports.zip app/build
  - curl -T reports.zip https://transfer.sh/reports.zip
